apiVersion: v1
kind: Pod
metadata:
  name: buildah-userns
  annotations:
    io.openshift.userns: "true"
    io.kubernetes.cri-o.userns-mode: "auto:size=65536;map-to-root=true"
spec:
  containers:
    - name: userns
      image: quay.io/mloriedo/buildah:userns
      securityContext:
        runAsUser: 1000650000
      volumeMounts:
        #- mountPath: /var/lib/containers
        #  name: container-storage
        - mountPath: /projects
          name: projects
      resources:
        limits:
          cpu: 100m
          memory: 1G
  volumes:
   #- name: container-storage
   #  emptyDir:
   #    medium: Memory
   - name: projects
     emptyDir: {}
      #resources:
      # limits:
      #   github.com/fuse: 1
